# Generated by Django 5.1.7 on 2025-06-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberjoinclass',
            unique_together={('sportclass', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('sportclass', 'user')},
        ),
    ]
