# Generated by Django 5.1.7 on 2025-05-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_sportclass_decription_alter_sportclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m'),
        ),
    ]
