# Generated by Django 5.2 on 2025-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_newfeed_options_rename_news_newfeed_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfeed',
            name='category',
            field=models.CharField(choices=[('training', 'Mẹo Luyện Tập'), ('nutrition', 'Chế Độ Dinh Dưỡng'), ('events', 'Sự Kiện Thể Thao')], default='training', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('employee', 'Employee')], default='member', max_length=20),
        ),
    ]
