# Generated by Django 5.1.7 on 2025-05-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclass',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.category'),
        ),
    ]
