# Generated by Django 5.2 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_newfeed_category_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('employee', 'Employee')], default='member', max_length=20),
        ),
    ]
