# Generated by Django 5.1.7 on 2025-05-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_sportclass_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach_Category',
        ),
    ]
