# Generated by Django 5.1.7 on 2025-05-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_sportclass_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sportclass',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
