# Generated by Django 5.2 on 2025-05-24 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_alter_user_role'),
        ('sports', '0008_schedule_place_sportclass_price'),
    ]

    operations = [
    ]
