# Generated by Django 5.2 on 2025-05-24 04:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_remove_sportclass_decription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfeed',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
